version: '3.1'

services:
  kafka:
    image: johnnypark/kafka-zookeeper
    ports:
      - 2181:2181
      - 9092:9092
    networks:
      - internal
    environment:
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
      ADVERTISED_PORT: 9092
      TOPICS: "chat.messages:2:1"
  db:
    image: postgres
    env_file:
      - ./.prodenv
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      - internal
    labels:
      - traefik.enable=false
  chat-server:
    image: chat-server
    build: .
    env_file:
      - ./.prodenv
    environment:
      NODE_ENV: production
      POSTGRES_HOST: db
      POSTGRES_DB: chatserverdb
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      KAFKA_TOPIC: chat.messages
      KAFKA_CLIENT_ID: "${KAFKA_CLIENT_ID}"
      KAFKA_HOST: kafka
      KAFKA_PORT: "${KAFKA_PORT}"
    ports:
      - 3001:3001
    labels:
      - traefik.backend=chat-server
      - traefik.frontend.rule=Host:nodechat.club
      - traefik.docker.network=proxy
      - traefik.port=80
    networks:
      - internal
      - proxy
    depends_on:
      - db
      - kafka
    command: ["./wait-for-it.sh", "db:5432", "--", "./wait-for-it.sh", "kafka:2181", "--", "ts-node", "./src/server.ts"]

networks:
  proxy:
    external: true
  internal:
    external: false
